export default {
  tintColor: '#2F95DC',
  tabIconDefault: '#ccc',
  tabIconSelected: '#2F95DC',
  tabBar: '#FEFEFE',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: '#ccc',
  noticeText: '#fff',
  frog: '#84BE6A',
  greenlantern: '#3D8B37',
  mint: '#DCF8C6',
  white: '#FFFFFF',
  black: '#000000',
  dimgray: '#696969',
};
